# Generated by Django 5.0.6 on 2024-06-02 00:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('idAlumno', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10, null=True)),
                ('nombre_ponente', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('ponencia', models.CharField(blank=True, max_length=200, null=True)),
                ('doctorado_maestria', models.CharField(blank=True, max_length=200, null=True)),
                ('unidad', models.CharField(blank=True, max_length=200, null=True)),
                ('mencion', models.CharField(blank=True, max_length=200, null=True)),
                ('sala', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_sustentacion', models.DateField(blank=True, null=True)),
                ('hora_inicio_sustentacion', models.TimeField(blank=True, null=True)),
                ('hora_fin_sustentacion', models.TimeField(blank=True, null=True)),
                ('asesor', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_actualizacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('eliminado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Jurado',
            fields=[
                ('idJurado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_jurado', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('idEvaluacion', models.AutoField(primary_key=True, serialize=False)),
                ('Originalidad', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('Importancia', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('Coherencia', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('Metodologia', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('Validez', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('Dominio_tema', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('puntajeFinal', models.IntegerField(default=0)),
                ('sugerencias', models.TextField(blank=True, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appevaluacion.alumno')),
                ('jurado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appevaluacion.jurado')),
            ],
        ),
    ]
