# Generated by Django 5.0.7 on 2024-11-19 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('idAlumno', models.AutoField(primary_key=True, serialize=False)),
                ('codigoAlumno', models.CharField(max_length=10, null=True)),
                ('nombre_ponente', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('dni', models.CharField(max_length=15, null=True)),
                ('ncelular', models.CharField(max_length=10, null=True)),
                ('ponencia', models.CharField(blank=True, max_length=200, null=True)),
                ('doctorado_maestria', models.CharField(blank=True, choices=[('DOCTORADO', 'DOCTORADO'), ('MAESTRIA', 'MAESTRIA')], max_length=200, null=True)),
                ('unidad', models.CharField(blank=True, choices=[('UNIDAD DE CIENCIAS ECONOMICAS', 'UNIDAD DE CIENCIAS ECONOMICAS'), ('UNIDAD DE DERECHO', 'UNIDAD DE DERECHO'), ('UNIDAD DE FARMACIA Y BIOQUIMICA', 'UNIDAD DE FARMACIA Y BIOQUIMICA'), ('UNIDAD DE CIENCIAS MEDICAS', 'UNIDAD DE CIENCIAS MEDICAS'), ('UNIDAD DE CIENCIAS SOCIALES', 'UNIDAD DE CIENCIAS SOCIALES'), ('UNIDAD DE INGENIERIA', 'UNIDAD DE INGENIERIA'), ('UNIDAD DE CIENCIAS BIOLOGICAS', 'UNIDAD DE CIENCIAS BIOLOGICAS'), ('UNIDAD DE CIENCIAS FISICAS Y MATEMATICAS', 'UNIDAD DE CIENCIAS FISICAS Y MATEMATICAS'), ('UNIDAD DE ENFERMERIA', 'UNIDAD DE ENFERMERIA'), ('UNIDAD DE ING. QUIMICA', 'UNIDAD DE ING. QUIMICA'), ('UNIDAD DE AGROPECUARIAS', 'UNIDAD DE AGROPECUARIAS'), ('UNIDAD DE EDUCACION', 'UNIDAD DE EDUCACION')], max_length=200, null=True)),
                ('mencion', models.CharField(blank=True, max_length=200, null=True)),
                ('sala', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_sustentacion', models.DateField(blank=True, null=True)),
                ('hora_inicio_sustentacion', models.TimeField(blank=True, null=True)),
                ('hora_fin_sustentacion', models.TimeField(blank=True, null=True)),
                ('asesor', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('idJornada', models.AutoField(primary_key=True, serialize=False)),
                ('codigoJornada', models.CharField(max_length=10, null=True)),
                ('descripJornada', models.CharField(max_length=200, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('idEvaluacion', models.AutoField(primary_key=True, serialize=False)),
                ('codigoEvaluacion', models.CharField(max_length=10, unique=True)),
                ('estadoFinal', models.IntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appevaluacion.alumno', unique=True)),
                ('jornada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appevaluacion.jornada')),
            ],
        ),
        migrations.AddField(
            model_name='alumno',
            name='jornadas',
            field=models.ManyToManyField(related_name='alumnos', to='appevaluacion.jornada'),
        ),
        migrations.CreateModel(
            name='Jurado',
            fields=[
                ('idJurado', models.AutoField(primary_key=True, serialize=False)),
                ('codigoJurado', models.CharField(max_length=10, null=True)),
                ('nombre_jurado', models.CharField(max_length=200)),
                ('dni', models.CharField(max_length=20, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(max_length=10, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('jornadas', models.ManyToManyField(related_name='jurados', to='appevaluacion.jornada')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleEvaluacion',
            fields=[
                ('idDetEvaluacion', models.AutoField(primary_key=True, serialize=False)),
                ('cargo', models.CharField(max_length=20)),
                ('originalidad', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1)),
                ('importancia', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1)),
                ('coherencia', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1)),
                ('metodologia', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1)),
                ('validez', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1)),
                ('dominio_tema', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1)),
                ('puntajeFinal', models.IntegerField(default=0)),
                ('estado', models.IntegerField(default=0)),
                ('sugerencias', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appevaluacion.alumno')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appevaluacion.evaluacion')),
                ('jornada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appevaluacion.jornada')),
                ('jurado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appevaluacion.jurado')),
            ],
        ),
    ]
