# Generated by Django 5.0.7 on 2024-07-30 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appevaluacion', '0002_remove_evaluacion_coherencia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleevaluacion',
            name='alumno',
        ),
        migrations.AddField(
            model_name='detalleevaluacion',
            name='cargo',
            field=models.CharField(default=True, max_length=20),
            preserve_default=False,
        ),
    ]
