# Generated by Django 5.0.6 on 2024-06-02 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appevaluacion', '0002_alter_alumno_fecha_actualizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='ncelular',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='dni',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
