# Generated by Django 5.0.7 on 2024-07-30 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appevaluacion', '0003_remove_detalleevaluacion_alumno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleevaluacion',
            name='alumno',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='appevaluacion.alumno'),
            preserve_default=False,
        ),
    ]
