# Generated by Django 5.0.6 on 2024-06-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appevaluacion', '0004_jurado_cargo_jurado_eliminado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jurado',
            name='cargo',
            field=models.CharField(choices=[('Presidente', 'Presidente'), ('Secretario', 'Secretario'), ('Vocal', 'Vocal')], max_length=20),
        ),
        migrations.AlterField(
            model_name='jurado',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='jurado',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
