# Generated by Django 5.0.7 on 2024-10-22 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appevaluacion', '0005_detalleevaluacion_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('idJornada', models.AutoField(primary_key=True, serialize=False)),
                ('codigoJornada', models.CharField(max_length=10, null=True)),
                ('descripJornada', models.CharField(max_length=200, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='alumno',
            old_name='codigo',
            new_name='codigoAlumno',
        ),
        migrations.RenameField(
            model_name='evaluacion',
            old_name='codigo',
            new_name='codigoEvaluacion',
        ),
        migrations.AddField(
            model_name='alumno',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='detalleevaluacion',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jurado',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jurado',
            name='codigoJurado',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='detalleevaluacion',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='jurado',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='jornadas',
            field=models.ManyToManyField(related_name='alumnos', to='appevaluacion.jornada'),
        ),
        migrations.AddField(
            model_name='jurado',
            name='jornadas',
            field=models.ManyToManyField(related_name='jurados', to='appevaluacion.jornada'),
        ),
    ]
