# Generated by Django 5.0.6 on 2024-06-02 17:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appevaluacion', '0005_alter_jurado_cargo_alter_jurado_fecha_actualizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='codigo',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='fecha_actualizacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
