# Generated by Django 5.0.7 on 2024-10-29 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appevaluacion', '0006_jornada_rename_codigo_alumno_codigoalumno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='jornada',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='appevaluacion.jornada'),
            preserve_default=False,
        ),
    ]
