# Generated by Django 5.0.7 on 2024-10-29 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appevaluacion', '0007_evaluacion_jornada'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleevaluacion',
            name='jornada',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='appevaluacion.jornada'),
            preserve_default=False,
        ),
    ]
