# Generated by Django 5.0.6 on 2024-06-02 19:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appevaluacion', '0007_alter_evaluacion_fecha_actualizacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluacion',
            name='Coherencia',
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='Dominio_tema',
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='Importancia',
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='Metodologia',
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='Originalidad',
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='Validez',
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='jurado',
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='puntajeFinal',
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='sugerencias',
        ),
        migrations.CreateModel(
            name='DetalleEvaluacion',
            fields=[
                ('idDetEvaluacion', models.AutoField(primary_key=True, serialize=False)),
                ('Originalidad', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('Importancia', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('Coherencia', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('Metodologia', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('Validez', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('Dominio_tema', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('puntajeFinal', models.IntegerField(default=0)),
                ('sugerencias', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False)),
                ('jurado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appevaluacion.jurado')),
            ],
        ),
    ]
