# Generated by Django 5.0.6 on 2024-06-02 19:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appevaluacion', '0008_remove_evaluacion_coherencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleevaluacion',
            name='evaluacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appevaluacion.evaluacion'),
        ),
        migrations.AlterField(
            model_name='detalleevaluacion',
            name='fecha_actualizacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='detalleevaluacion',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
