# Generated by Django 5.0.7 on 2024-10-31 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appevaluacion', '0009_evaluacion_estadofinal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='doctorado_maestria',
            field=models.CharField(blank=True, choices=[('DOCTORADO', 'DOCTORADO'), ('MAESTRIA', 'MAESTRIA')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='unidad',
            field=models.CharField(blank=True, choices=[('UNIDAD DE CIENCIAS_ECONOMICAS', 'UNIDAD DE CIENCIAS_ECONOMICAS'), ('UNIDAD DE DERECHO', 'UNIDAD DE DERECHO'), ('UNIDAD DE FARMACIA Y BIOQUIMICA', 'UNIDAD DE FARMACIA Y BIOQUIMICA'), ('UNIDAD DE CIENCIAS_MEDICAS', 'UNIDAD DE CIENCIAS_MEDICAS'), ('UNIDAD DE CIENCIAS_SOCIALES', 'UNIDAD DE CIENCIAS_SOCIALES'), ('UNIDAD DE INGENIERIA', 'UNIDAD DE INGENIERIA'), ('UNIDAD DE CIENCIAS BIOLOGICAS', 'UNIDAD DE CIENCIAS BIOLOGICAS'), ('UNIDAD DE CIENCIAS FISICAS Y MATEMATICAS', 'UNIDAD DE CIENCIAS FISICAS Y MATEMATICAS'), ('UNIDAD DE ENFERMERIA', 'UNIDAD DE ENFERMERIA'), ('UNIDAD DE ING. QUIMICA', 'UNIDAD DE ING. QUIMICA'), ('UNIDAD DE AGROPECUARIAS', 'UNIDAD DE AGROPECUARIAS'), ('UNIDAD DE EDUCACION', 'UNIDAD DE EDUCACION')], max_length=200, null=True),
        ),
    ]
