# Generated by Django 5.0.6 on 2024-06-02 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appevaluacion', '0009_detalleevaluacion_evaluacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleevaluacion',
            name='evaluacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appevaluacion.evaluacion'),
        ),
    ]
