# Generated by Django 5.0.6 on 2024-06-03 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appevaluacion', '0010_alter_detalleevaluacion_evaluacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleevaluacion',
            name='alumno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appevaluacion.alumno'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detalleevaluacion',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='detalleevaluacion',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
