# Generated by Django 5.0.7 on 2024-07-22 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appevaluacion', '0014_jurado_dni_jurado_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appevaluacion.alumno', unique=True),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='codigo',
            field=models.CharField(default=True, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
